default:
  before_script:
    - pip install tox

.py35:
  image: python:3.5

.py36:
  image: python:3.6

.py37:
  image: python:3.7

.py38:
  image: python:3.8

py35-django22:
  extends: .py35
  script:
    - tox -e py35-django22

py36-django22:
  extends: .py36
  script:
    - tox -e py36-django22

py37-django22:
  extends: .py37
  script:
    - tox -e py37-django22

py38-django22:
  extends: .py38
  script:
    - tox -e py38-django22

py36-django31:
  extends: .py36
  script:
    - tox -e py36-django31

py37-django31:
  extends: .py37
  script:
    - tox -e py37-django31

py38-django31:
  extends: .py38
  script:
    - tox -e py38-django31

lint:
  extends: .py37
  script:
    - tox -e lint

docs:
  image: python:3.7-alpine
  script:
    - tox -e docs
  except:
    - main

pages:
  stage: deploy
  image: python:3.7-alpine
  script:
    - tox -e docs-public
  artifacts:
    paths:
      - public
  only:
    - main
